### ISSUE TITLE
request undefined

### ISSUE THREAD

**Issue by sebastian-diedrich** [Anteru/liara#4]
Hi,

got the following error if I try to execute: 

`{% if request.endpoint.endswith(endpoint) %}`

command line said:

`jinja2.exceptions.UndefinedError: 'request' is undefined`

I'm new to Liara, under Flask its working when I importing request over app.py?

Kind regards!
Sebastian

**Comment by Anteru** [comment]
I'm not sure what you're trying to achieve here. Liara is a static page generator, so you run Liara and get a set of HTML pages. What are you doing with Flask here? It looks like you're trying to access the `request` object inside a template, but I fail to see how Liara is involved here. Liara doesn't have a global `request`object to use in templates.

**Comment by sebastian-diedrich** [comment]
I try to achieve a simple navigation where the active/current navigation point is highlighted. Just some minimalistic essentials for a website or blog. Nevermind I search for another static site generator. Thanks for your fast reply. BR


Am 24.09.2022 um 14:25 schrieb Matthäus G. Chajdas ***@***.***>:

﻿

I'm not sure what you're trying to achieve here. Liara is a static page generator, so you run Liara and get a set of HTML pages. What are you doing with Flask here? It looks like you're trying to access the request object inside a template, but I fail to see how Liara is involved here. Liara doesn't have a global requestobject to use in templates.

**Comment by Anteru** [comment]
FWIW, what you're trying to achieve is fairly easy in Liara: You can use `page.url.startswith(...)` to check the current page's URL. Assuming you have a menu somewhere in a [data file](https://liara-web.readthedocs.io/en/latest/content.html#data-files), you could use something like:
```jinja2
{% for item in site.data.menu %}
<li {% if page.url.startswith(item.url) %}class="active"{% endif %}>
	<a href="{{ item.url }}">{{ item.title }}</a>
</li>
{% endfor %}
```
